services:
  database:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: hugo_autopote_db
      MARIADB_USER: hugo_autopote_user
      MARIADB_PASSWORD: hugo_autopote_pwd
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  database_data:
